// <auto-generated />
using System;
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StockQuantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductBatchId");

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000001-0000-0000-0000-000000000001"),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductBatchId = new Guid("20000001-0000-0000-0000-000000000001"),
                            StockQuantity = 150m
                        },
                        new
                        {
                            Id = new Guid("30000002-0000-0000-0000-000000000002"),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductBatchId = new Guid("20000002-0000-0000-0000-000000000002"),
                            StockQuantity = 80m
                        },
                        new
                        {
                            Id = new Guid("30000003-0000-0000-0000-000000000003"),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductBatchId = new Guid("20000003-0000-0000-0000-000000000003"),
                            StockQuantity = 200m
                        },
                        new
                        {
                            Id = new Guid("30000004-0000-0000-0000-000000000004"),
                            LocationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductBatchId = new Guid("20000004-0000-0000-0000-000000000004"),
                            StockQuantity = 120m
                        },
                        new
                        {
                            Id = new Guid("30000005-0000-0000-0000-000000000005"),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductBatchId = new Guid("20000005-0000-0000-0000-000000000005"),
                            StockQuantity = 50m
                        },
                        new
                        {
                            Id = new Guid("30000006-0000-0000-0000-000000000006"),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductBatchId = new Guid("20000007-0000-0000-0000-000000000007"),
                            StockQuantity = 300m
                        },
                        new
                        {
                            Id = new Guid("30000007-0000-0000-0000-000000000007"),
                            LocationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductBatchId = new Guid("2000000a-0000-0000-0000-00000000000a"),
                            StockQuantity = 220m
                        },
                        new
                        {
                            Id = new Guid("30000008-0000-0000-0000-000000000008"),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductBatchId = new Guid("2000000b-0000-0000-0000-00000000000b"),
                            StockQuantity = 60m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Locations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWareHouse")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Av. Principal 123",
                            City = "Ciudad A",
                            IsActive = true,
                            IsWareHouse = true,
                            Name = "Bodega Central"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Calle Norte 45",
                            City = "Ciudad B",
                            IsActive = true,
                            IsWareHouse = true,
                            Name = "Bodega Norte"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "Plaza 8 #12",
                            City = "Ciudad A",
                            IsActive = true,
                            IsWareHouse = false,
                            Name = "Tienda Centro"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "Av. Sur 77",
                            City = "Ciudad C",
                            IsActive = true,
                            IsWareHouse = false,
                            Name = "Tienda Sur"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Address = "Km 10 Ruta",
                            City = "Ciudad D",
                            IsActive = false,
                            IsWareHouse = true,
                            Name = "Depósito Temporal"
                        });
                });

            modelBuilder.Entity("Domain.Entities.OutboundDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutboundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("OutboundId");

                    b.HasIndex("ProductBatchId");

                    b.ToTable("OutboundDetails", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000001-0000-0000-0000-000000000001"),
                            OutboundId = new Guid("40000001-0000-0000-0000-000000000001"),
                            ProductBatchId = new Guid("20000001-0000-0000-0000-000000000001"),
                            Quantity = 10m,
                            SubTotal = 55.0m
                        },
                        new
                        {
                            Id = new Guid("50000002-0000-0000-0000-000000000002"),
                            OutboundId = new Guid("40000001-0000-0000-0000-000000000001"),
                            ProductBatchId = new Guid("20000005-0000-0000-0000-000000000005"),
                            Quantity = 5m,
                            SubTotal = 225.0m
                        },
                        new
                        {
                            Id = new Guid("50000003-0000-0000-0000-000000000003"),
                            OutboundId = new Guid("40000002-0000-0000-0000-000000000002"),
                            ProductBatchId = new Guid("20000003-0000-0000-0000-000000000003"),
                            Quantity = 20m,
                            SubTotal = 64.0m
                        },
                        new
                        {
                            Id = new Guid("50000004-0000-0000-0000-000000000004"),
                            OutboundId = new Guid("40000003-0000-0000-0000-000000000003"),
                            ProductBatchId = new Guid("20000006-0000-0000-0000-000000000006"),
                            Quantity = 2m,
                            SubTotal = 120.0m
                        },
                        new
                        {
                            Id = new Guid("50000005-0000-0000-0000-000000000005"),
                            OutboundId = new Guid("40000003-0000-0000-0000-000000000003"),
                            ProductBatchId = new Guid("20000007-0000-0000-0000-000000000007"),
                            Quantity = 15m,
                            SubTotal = 180.0m
                        },
                        new
                        {
                            Id = new Guid("50000006-0000-0000-0000-000000000006"),
                            OutboundId = new Guid("40000005-0000-0000-0000-000000000005"),
                            ProductBatchId = new Guid("2000000b-0000-0000-0000-00000000000b"),
                            Quantity = 3m,
                            SubTotal = 285.0m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Outbounds", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OutboundDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutboundNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OutboundUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReceivedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginLocationId");

                    b.HasIndex("OutboundNumber")
                        .IsUnique();

                    b.HasIndex("OutboundUserId");

                    b.HasIndex("ReceivedUserId");

                    b.ToTable("Outbounds", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000001-0000-0000-0000-000000000001"),
                            DestinationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            OriginLocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OutboundDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OutboundNumber = "OUT-0001",
                            OutboundUserId = new Guid("10000001-0000-0000-0000-000000000001"),
                            Status = "EnviadaASucursal"
                        },
                        new
                        {
                            Id = new Guid("40000002-0000-0000-0000-000000000002"),
                            DestinationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            OriginLocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            OutboundDate = new DateTime(2026, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OutboundNumber = "OUT-0002",
                            OutboundUserId = new Guid("10000004-0000-0000-0000-000000000004"),
                            Status = "EnviadaASucursal"
                        },
                        new
                        {
                            Id = new Guid("40000003-0000-0000-0000-000000000003"),
                            DestinationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            OriginLocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OutboundDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OutboundNumber = "OUT-0003",
                            OutboundUserId = new Guid("10000002-0000-0000-0000-000000000002"),
                            ReceivedDate = new DateTime(2025, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceivedUserId = new Guid("10000005-0000-0000-0000-000000000005"),
                            Status = "RecibidoEnSucursal"
                        },
                        new
                        {
                            Id = new Guid("40000004-0000-0000-0000-000000000004"),
                            DestinationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            OriginLocationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            OutboundDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OutboundNumber = "OUT-0004",
                            OutboundUserId = new Guid("10000007-0000-0000-0000-000000000007"),
                            Status = "EnviadaASucursal"
                        },
                        new
                        {
                            Id = new Guid("40000005-0000-0000-0000-000000000005"),
                            DestinationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OriginLocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            OutboundDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OutboundNumber = "OUT-0005",
                            OutboundUserId = new Guid("10000006-0000-0000-0000-000000000006"),
                            ReceivedDate = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReceivedUserId = new Guid("10000001-0000-0000-0000-000000000001"),
                            Status = "RecibidoEnSucursal"
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductBatches", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductBatches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000001-0000-0000-0000-000000000001"),
                            BatchNumber = "BATCH-1001",
                            ExpirationDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("00000001-0000-0000-0000-000000000001"),
                            Quantity = 150m,
                            UnitCost = 5.50m
                        },
                        new
                        {
                            Id = new Guid("20000002-0000-0000-0000-000000000002"),
                            BatchNumber = "BATCH-1002",
                            ExpirationDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("00000001-0000-0000-0000-000000000001"),
                            Quantity = 80m,
                            UnitCost = 5.75m
                        },
                        new
                        {
                            Id = new Guid("20000003-0000-0000-0000-000000000003"),
                            BatchNumber = "BATCH-2001",
                            ExpirationDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("00000002-0000-0000-0000-000000000002"),
                            Quantity = 200m,
                            UnitCost = 3.20m
                        },
                        new
                        {
                            Id = new Guid("20000004-0000-0000-0000-000000000004"),
                            BatchNumber = "BATCH-2002",
                            ExpirationDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductId = new Guid("00000002-0000-0000-0000-000000000002"),
                            Quantity = 120m,
                            UnitCost = 3.00m
                        },
                        new
                        {
                            Id = new Guid("20000005-0000-0000-0000-000000000005"),
                            BatchNumber = "BATCH-3001",
                            ExpirationDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("00000003-0000-0000-0000-000000000003"),
                            Quantity = 50m,
                            UnitCost = 45.00m
                        },
                        new
                        {
                            Id = new Guid("20000006-0000-0000-0000-000000000006"),
                            BatchNumber = "BATCH-4001",
                            ExpirationDate = new DateTime(2028, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("00000004-0000-0000-0000-000000000004"),
                            Quantity = 40m,
                            UnitCost = 60.00m
                        },
                        new
                        {
                            Id = new Guid("20000007-0000-0000-0000-000000000007"),
                            BatchNumber = "BATCH-5001",
                            ExpirationDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("00000005-0000-0000-0000-000000000005"),
                            Quantity = 300m,
                            UnitCost = 12.00m
                        },
                        new
                        {
                            Id = new Guid("20000008-0000-0000-0000-000000000008"),
                            BatchNumber = "BATCH-6001",
                            ExpirationDate = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("00000006-0000-0000-0000-000000000006"),
                            Quantity = 90m,
                            UnitCost = 110.00m
                        },
                        new
                        {
                            Id = new Guid("20000009-0000-0000-0000-000000000009"),
                            BatchNumber = "BATCH-7001",
                            ExpirationDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductId = new Guid("00000007-0000-0000-0000-000000000007"),
                            Quantity = 180m,
                            UnitCost = 25.00m
                        },
                        new
                        {
                            Id = new Guid("2000000a-0000-0000-0000-00000000000a"),
                            BatchNumber = "BATCH-8001",
                            ExpirationDate = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductId = new Guid("00000008-0000-0000-0000-000000000008"),
                            Quantity = 220m,
                            UnitCost = 8.50m
                        },
                        new
                        {
                            Id = new Guid("2000000b-0000-0000-0000-00000000000b"),
                            BatchNumber = "BATCH-9001",
                            ExpirationDate = new DateTime(2029, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("00000009-0000-0000-0000-000000000009"),
                            Quantity = 60m,
                            UnitCost = 95.00m
                        },
                        new
                        {
                            Id = new Guid("2000000c-0000-0000-0000-00000000000c"),
                            BatchNumber = "BATCH-10001",
                            ExpirationDate = new DateTime(2027, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("0000000a-0000-0000-0000-00000000000a"),
                            Quantity = 70m,
                            UnitCost = 40.00m
                        },
                        new
                        {
                            Id = new Guid("2000000d-0000-0000-0000-00000000000d"),
                            BatchNumber = "BATCH-11001",
                            ExpirationDate = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductId = new Guid("0000000b-0000-0000-0000-00000000000b"),
                            Quantity = 140m,
                            UnitCost = 22.50m
                        },
                        new
                        {
                            Id = new Guid("2000000e-0000-0000-0000-00000000000e"),
                            BatchNumber = "BATCH-12001",
                            ExpirationDate = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductId = new Guid("0000000c-0000-0000-0000-00000000000c"),
                            Quantity = 95m,
                            UnitCost = 18.00m
                        },
                        new
                        {
                            Id = new Guid("2000000f-0000-0000-0000-00000000000f"),
                            BatchNumber = "BATCH-13001",
                            ExpirationDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("0000000d-0000-0000-0000-00000000000d"),
                            Quantity = 260m,
                            UnitCost = 4.00m
                        },
                        new
                        {
                            Id = new Guid("20000010-0000-0000-0000-000000000010"),
                            BatchNumber = "BATCH-14001",
                            ExpirationDate = new DateTime(2028, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("0000000e-0000-0000-0000-00000000000e"),
                            Quantity = 30m,
                            UnitCost = 150.00m
                        },
                        new
                        {
                            Id = new Guid("20000011-0000-0000-0000-000000000011"),
                            BatchNumber = "BATCH-15001",
                            ExpirationDate = new DateTime(2027, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            ProductId = new Guid("0000000f-0000-0000-0000-00000000000f"),
                            Quantity = 110m,
                            UnitCost = 2.50m
                        },
                        new
                        {
                            Id = new Guid("20000012-0000-0000-0000-000000000012"),
                            BatchNumber = "BATCH-16001",
                            ExpirationDate = new DateTime(2029, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ProductId = new Guid("00000010-0000-0000-0000-000000000010"),
                            Quantity = 45m,
                            UnitCost = 180.00m
                        },
                        new
                        {
                            Id = new Guid("20000013-0000-0000-0000-000000000013"),
                            BatchNumber = "BATCH-17001",
                            ExpirationDate = new DateTime(2026, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            ProductId = new Guid("00000011-0000-0000-0000-000000000011"),
                            Quantity = 55m,
                            UnitCost = 210.00m
                        },
                        new
                        {
                            Id = new Guid("20000014-0000-0000-0000-000000000014"),
                            BatchNumber = "BATCH-18001",
                            ExpirationDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ProductId = new Guid("00000012-0000-0000-0000-000000000012"),
                            Quantity = 400m,
                            UnitCost = 75.00m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000001"),
                            Brand = "Genfar",
                            IsActive = true,
                            Name = "Paracetamol 500mg",
                            Sku = "MED-PAR500"
                        },
                        new
                        {
                            Id = new Guid("00000002-0000-0000-0000-000000000002"),
                            Brand = "Advil",
                            IsActive = true,
                            Name = "Ibuprofeno 400mg",
                            Sku = "MED-IBU400"
                        },
                        new
                        {
                            Id = new Guid("00000003-0000-0000-0000-000000000003"),
                            Brand = "GSK",
                            IsActive = true,
                            Name = "Amoxicilina 500mg",
                            Sku = "MED-AMO500"
                        },
                        new
                        {
                            Id = new Guid("00000004-0000-0000-0000-000000000004"),
                            Brand = "Bayer",
                            IsActive = true,
                            Name = "Loratadina 10mg",
                            Sku = "MED-LOR10"
                        },
                        new
                        {
                            Id = new Guid("00000005-0000-0000-0000-000000000005"),
                            Brand = "Merck",
                            IsActive = true,
                            Name = "Metformina 500mg",
                            Sku = "MED-MET500"
                        },
                        new
                        {
                            Id = new Guid("00000006-0000-0000-0000-000000000006"),
                            Brand = "Pfizer",
                            IsActive = true,
                            Name = "Atorvastatina 20mg",
                            Sku = "MED-ATR20"
                        },
                        new
                        {
                            Id = new Guid("00000007-0000-0000-0000-000000000007"),
                            Brand = "Ventolin",
                            IsActive = true,
                            Name = "Salbutamol Inhalador",
                            Sku = "MED-SAL100"
                        },
                        new
                        {
                            Id = new Guid("00000008-0000-0000-0000-000000000008"),
                            Brand = "AstraZeneca",
                            IsActive = true,
                            Name = "Omeprazol 20mg",
                            Sku = "MED-OMP20"
                        },
                        new
                        {
                            Id = new Guid("00000009-0000-0000-0000-000000000009"),
                            Brand = "MK",
                            IsActive = true,
                            Name = "Losartán 50mg",
                            Sku = "MED-LOS50"
                        },
                        new
                        {
                            Id = new Guid("0000000a-0000-0000-0000-00000000000a"),
                            Brand = "Bayer",
                            IsActive = true,
                            Name = "Aspirina 100mg",
                            Sku = "MED-ASP100"
                        },
                        new
                        {
                            Id = new Guid("0000000b-0000-0000-0000-00000000000b"),
                            Brand = "Laboratorios Stein",
                            IsActive = true,
                            Name = "Dexametasona 4mg",
                            Sku = "MED-DEX4"
                        },
                        new
                        {
                            Id = new Guid("0000000c-0000-0000-0000-00000000000c"),
                            Brand = "Abbott",
                            IsActive = true,
                            Name = "Cefalexina 500mg",
                            Sku = "MED-CEP500"
                        },
                        new
                        {
                            Id = new Guid("0000000d-0000-0000-0000-00000000000d"),
                            Brand = "Sandoz",
                            IsActive = true,
                            Name = "Azitromicina 500mg",
                            Sku = "MED-AZI500"
                        },
                        new
                        {
                            Id = new Guid("0000000e-0000-0000-0000-00000000000e"),
                            Brand = "Sanofi",
                            IsActive = true,
                            Name = "Enalapril 10mg",
                            Sku = "MED-ENL10"
                        },
                        new
                        {
                            Id = new Guid("0000000f-0000-0000-0000-00000000000f"),
                            Brand = "Roche",
                            IsActive = true,
                            Name = "Clonazepam 2mg",
                            Sku = "MED-CLO2"
                        },
                        new
                        {
                            Id = new Guid("00000010-0000-0000-0000-000000000010"),
                            Brand = "Voltaren",
                            IsActive = true,
                            Name = "Diclofenaco 50mg",
                            Sku = "MED-DIC50"
                        },
                        new
                        {
                            Id = new Guid("00000011-0000-0000-0000-000000000011"),
                            Brand = "Siegfried",
                            IsActive = true,
                            Name = "Ketorolaco 10mg",
                            Sku = "MED-KET10"
                        },
                        new
                        {
                            Id = new Guid("00000012-0000-0000-0000-000000000012"),
                            Brand = "Zoloft",
                            IsActive = true,
                            Name = "Sertralina 50mg",
                            Sku = "MED-SER50"
                        },
                        new
                        {
                            Id = new Guid("00000013-0000-0000-0000-000000000013"),
                            Brand = "Euthyrox",
                            IsActive = true,
                            Name = "Levotiroxina 50mcg",
                            Sku = "MED-LEV50"
                        },
                        new
                        {
                            Id = new Guid("00000014-0000-0000-0000-000000000014"),
                            Brand = "Flanax",
                            IsActive = true,
                            Name = "Naproxeno 500mg",
                            Sku = "MED-NAP500"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Jefe de Bodega"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Operario de Bodega"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecondLastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LocationId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000001-0000-0000-0000-000000000001"),
                            Email = "c.gonzalez@example.com",
                            FirstName = "Carlos",
                            FullName = "Carlos Miguel Gonzalez Lopez",
                            IsActive = true,
                            LastName = "Gonzalez",
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PasswordHash = "HASHED_pw1",
                            RoleId = 1,
                            SecondLastName = "Lopez",
                            SecondName = "Miguel",
                            UserName = "cgonzalez"
                        },
                        new
                        {
                            Id = new Guid("10000002-0000-0000-0000-000000000002"),
                            Email = "m.perez@example.com",
                            FirstName = "Mariana",
                            FullName = "Mariana Elena Perez Soto",
                            IsActive = true,
                            LastName = "Perez",
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PasswordHash = "HASHED_pw2",
                            RoleId = 2,
                            SecondLastName = "Soto",
                            SecondName = "Elena",
                            UserName = "mperez"
                        },
                        new
                        {
                            Id = new Guid("10000003-0000-0000-0000-000000000003"),
                            Email = "j.ramirez@example.com",
                            FirstName = "Javier",
                            FullName = "Javier Ramirez",
                            IsActive = true,
                            LastName = "Ramirez",
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PasswordHash = "HASHED_pw3",
                            RoleId = 2,
                            SecondLastName = "",
                            SecondName = "",
                            UserName = "jramirez"
                        },
                        new
                        {
                            Id = new Guid("10000004-0000-0000-0000-000000000004"),
                            Email = "l.martinez@example.com",
                            FirstName = "Lucia",
                            FullName = "Lucia Beatriz Martinez Diaz",
                            IsActive = true,
                            LastName = "Martinez",
                            LocationId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PasswordHash = "HASHED_pw4",
                            RoleId = 1,
                            SecondLastName = "Diaz",
                            SecondName = "Beatriz",
                            UserName = "lmartinez"
                        },
                        new
                        {
                            Id = new Guid("10000005-0000-0000-0000-000000000005"),
                            Email = "p.sanchez@example.com",
                            FirstName = "Pedro",
                            FullName = "Pedro Alberto Sanchez",
                            IsActive = true,
                            LastName = "Sanchez",
                            LocationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PasswordHash = "HASHED_pw5",
                            RoleId = 2,
                            SecondLastName = "",
                            SecondName = "Alberto",
                            UserName = "psanchez"
                        },
                        new
                        {
                            Id = new Guid("10000006-0000-0000-0000-000000000006"),
                            Email = "a.torres@example.com",
                            FirstName = "Ana",
                            FullName = "Ana Torres",
                            IsActive = true,
                            LastName = "Torres",
                            LocationId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PasswordHash = "HASHED_pw6",
                            RoleId = 2,
                            SecondLastName = "",
                            SecondName = "",
                            UserName = "atorres"
                        },
                        new
                        {
                            Id = new Guid("10000007-0000-0000-0000-000000000007"),
                            Email = "r.vega@example.com",
                            FirstName = "Roberto",
                            FullName = "Roberto Vega",
                            IsActive = true,
                            LastName = "Vega",
                            LocationId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PasswordHash = "HASHED_pw7",
                            RoleId = 2,
                            SecondLastName = "",
                            SecondName = "",
                            UserName = "rvega"
                        },
                        new
                        {
                            Id = new Guid("10000008-0000-0000-0000-000000000008"),
                            Email = "s.rios@example.com",
                            FirstName = "Sandra",
                            FullName = "Sandra Mar Rios Garcia",
                            IsActive = true,
                            LastName = "Rios",
                            LocationId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PasswordHash = "HASHED_pw8",
                            RoleId = 1,
                            SecondLastName = "Garcia",
                            SecondName = "Mar",
                            UserName = "srios"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Domain.Entities.Locations", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductBatches", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("ProductBatch");
                });

            modelBuilder.Entity("Domain.Entities.OutboundDetails", b =>
                {
                    b.HasOne("Domain.Entities.Outbounds", "Outbound")
                        .WithMany()
                        .HasForeignKey("OutboundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductBatches", "ProductBatch")
                        .WithMany()
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Outbound");

                    b.Navigation("ProductBatch");
                });

            modelBuilder.Entity("Domain.Entities.Outbounds", b =>
                {
                    b.HasOne("Domain.Entities.Locations", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Locations", "OriginLocation")
                        .WithMany()
                        .HasForeignKey("OriginLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users", "OutboundUser")
                        .WithMany()
                        .HasForeignKey("OutboundUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users", "ReceivedUser")
                        .WithMany()
                        .HasForeignKey("ReceivedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Destination");

                    b.Navigation("OriginLocation");

                    b.Navigation("OutboundUser");

                    b.Navigation("ReceivedUser");
                });

            modelBuilder.Entity("Domain.Entities.ProductBatches", b =>
                {
                    b.HasOne("Domain.Entities.Locations", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Products", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Users", b =>
                {
                    b.HasOne("Domain.Entities.Locations", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
